"""Extended reviewed scenarios for the deterministic mission catalog."""

from __future__ import annotations

from .mission_archetypes_core import _outcomes
from .mission_catalog_models import ScenarioArchetype

EXTENDED_SCENARIO_ARCHETYPES: tuple[ScenarioArchetype, ...] = (
    ScenarioArchetype(
        id="science.present_comparison",
        title="Present a comparison from supplied data",
        context_family="science",
        premise="A real open dataset or reproducible experiment supplies two sets of measurements, a visible pattern, and a stated limitation or competing interpretation.",
        learner_role="learner presenting what the comparison shows and what it implies",
        partner_roles=("classmate", "teacher", "study partner"),
        setting_slots=("real accessible topic", "open dataset or reproducible experiment", "key difference", "stated limitation or competing interpretation"),
        text_types=("comparison table", "bar chart description", "presentation dialogue"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication"),
        compatible_interest_ids=("science", "education", "technology", "sports"),
        outcomes=_outcomes(
            ("Can identify which group is larger or smaller in a simple supplied table.", "a short comparison statement", "labelled columns and fixed comparison frames"),
            ("Can describe the key difference between two groups and say what it shows.", "a brief comparison with a simple conclusion", "a small table and useful phrases"),
            ("Can present the main finding from a supplied dataset and connect it to a supported interpretation.", "a clear evidence-linked comparison", "the complete dataset and criteria"),
            ("Can weigh supported interpretations, qualify a conclusion using the stated limitation, and respond to an alternative reading.", "a cautious qualified comparison with a response to the alternative", "the self-contained dataset and stated limitation only"),
        ),
    ),
    ScenarioArchetype(
        id="culture.respond_to_shared_story",
        title="Respond to a real published story",
        context_family="culture",
        premise="A public-domain, licensed, or community-authorized extract from a real published story presents a character's choice, an implied theme, and a supplied parallel situation without treating one story as representative of an entire culture.",
        learner_role="reader giving a text-grounded response and connecting it to a wider idea",
        partner_roles=("friend", "classmate", "reading-group member"),
        setting_slots=("source-authorized published extract", "character choice", "implied theme", "parallel situation or alternative interpretation"),
        text_types=("story extract", "short reflection", "discussion exchange"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("culture", "education", "entertainment", "history"),
        outcomes=_outcomes(
            ("Can identify a character's action and give a simple reaction to it.", "a short reaction to the story", "a brief illustrated extract and sentence frames"),
            ("Can describe what a character did and give a view with a reason from the extract.", "a short supported response", "the extract and a phrase bank"),
            ("Can summarize the character's choice, identify the implied theme, and connect it to the supplied parallel situation.", "a connected text-grounded reflection", "the extract, parallel situation, and reflection criteria"),
            ("Can analyse a theme across the published story extract, qualify a moral reading, and engage with an alternative view.", "a nuanced response grounded in the text", "the self-contained extract only"),
        ),
    ),
    ScenarioArchetype(
        id="everyday.give_and_receive_directions",
        title="Give or follow directions",
        context_family="everyday",
        premise="A real public map extract and a dated or simulated route update supply all landmarks, street names, turns, and any obstacle needed to complete or revise a route.",
        learner_role="person explaining or following a route using only the supplied map details",
        partner_roles=("passerby", "neighbour", "friend"),
        setting_slots=("real public map extract", "start point", "destination", "dated or simulated route obstacle"),
        text_types=("neighbourhood map", "written directions", "street dialogue"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("daily_life", "travel", "culture", "sports", "entertainment"),
        outcomes=_outcomes(
            ("Can follow one or two direction steps using supplied landmarks.", "a short confirmed route", "a simple map and fixed direction phrases"),
            ("Can give or follow a short route using familiar landmarks and direction words.", "a brief set of accurate directions", "a clear map and a phrase bank"),
            ("Can explain a multi-step route, account for one complication, and confirm understanding.", "a clear complete set of directions", "the supplied map and task criteria only"),
            ("Can give precise directions, use a supplied obstacle update to adapt the route, and explain the change.", "a revised route with a clear explanation of the change", "the supplied map, obstacle update, and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="everyday.ask_for_and_give_recommendations",
        title="Ask for and give a recommendation",
        context_family="everyday",
        premise="A real local area supplies recognizable restaurants, shops, events, or services, while dated source details or clearly labelled practice cards provide the features, comments, and trade-offs used for the decision.",
        learner_role="person asking for or giving a justified recommendation",
        partner_roles=("friend", "neighbour", "local guide"),
        setting_slots=("options with ratings", "requester's preferences", "relevant trade-offs", "decision criteria for a defensible best fit"),
        text_types=("review snippets", "recommendation message", "conversation exchange"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "exam_preparation"),
        compatible_interest_ids=("daily_life", "travel", "entertainment", "culture"),
        outcomes=_outcomes(
            ("Can read a simple rating and suggest one option for a familiar need.", "a short suggestion", "labelled options and a fixed suggestion frame"),
            ("Can compare two options and suggest the better one with a simple reason.", "a brief recommendation with a reason", "a small review card and comparison phrases"),
            ("Can evaluate several options against stated preferences and recommend one with supporting evidence.", "a justified recommendation that addresses the drawback", "the review data and criteria"),
            ("Can weigh subtle trade-offs, qualify a recommendation, and respond to a challenge using the stated criteria.", "a nuanced recommendation that acknowledges the main trade-off", "the evidence, decision criteria, and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="travel.describe_a_place",
        title="Describe a real place",
        context_family="travel",
        premise="A real place is introduced through stable source-grounded physical, cultural, and practical details sufficient for a description without specialist knowledge.",
        learner_role="traveler describing the place to someone who has not been there",
        partner_roles=("friend", "travel companion", "host"),
        setting_slots=("real place", "source-grounded key features", "practical details", "personal highlight"),
        text_types=("travel note", "postcard-style message", "description dialogue"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("daily_life", "travel", "entertainment", "culture"),
        outcomes=_outcomes(
            ("Can name a place and say one or two things about it.", "a short place description", "a labelled picture and sentence frames"),
            ("Can describe the main features of a real place using simple sentences.", "a brief description with two or three details", "a short fact card and phrase bank"),
            ("Can give an organised description of a real place, covering features, atmosphere, and a practical detail.", "a connected multi-point description", "the place details and task criteria only"),
            ("Can describe a real place vividly, contrast aspects, and include a qualified personal evaluation.", "a rich description with contrast and opinion", "the supplied details only"),
        ),
    ),
    ScenarioArchetype(
        id="travel.prepare_for_a_trip",
        title="Prepare for a trip to a real destination",
        context_family="travel",
        premise="A real destination is paired with stable descriptive facts and a clearly labelled practice brief; any entry rules, prices, availability, or schedules must be dated official evidence or explicitly simulated rather than presented as current travel advice.",
        learner_role="traveler preparing by checking requirements and making a practical plan",
        partner_roles=("travel companion", "agent", "host"),
        setting_slots=("real destination", "dated official or simulated entry details", "packing checklist", "practice budget"),
        text_types=("trip brief", "preparation checklist", "planning dialogue"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "workplace_communication"),
        compatible_interest_ids=("travel", "daily_life", "culture", "entertainment"),
        outcomes=_outcomes(
            ("Can find key trip details such as what to bring and when to leave from a simple list.", "a short checklist confirmation", "a labelled trip card and sentence frames"),
            ("Can summarize the main preparation steps and ask one practical question.", "a brief preparation summary and a question", "a simple brief and phrase bank"),
            ("Can organise preparation steps, explain a supplied entry detail, and flag a potential problem.", "a clear preparation plan with a flagged issue", "the trip brief and task criteria only"),
            ("Can synthesize requirements, evaluate a budget constraint, and propose a contingency.", "a detailed preparation plan with a contingency", "the complete brief and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="work.give_and_respond_to_feedback",
        title="Give and respond to feedback",
        context_family="work",
        premise="A realistic work sample about a real-world subject has a clear goal and supplied reviewer comments that can be addressed without specialist knowledge or attribution to a real employer.",
        learner_role="colleague giving constructive feedback or responding to it professionally",
        partner_roles=("colleague", "team lead", "project partner"),
        setting_slots=("work output", "stated goal", "reviewed strengths and changes", "revision constraints and priorities"),
        text_types=("review note", "feedback exchange", "revision message"),
        compatible_goal_ids=("workplace_communication", "academic_study", "confident_conversation"),
        compatible_interest_ids=("business", "education", "technology", "science"),
        outcomes=_outcomes(
            ("Can identify one positive and one change from a simple review note.", "a short feedback acknowledgment", "labelled comments and fixed response frames"),
            ("Can summarize the main feedback and say what change to make.", "a brief feedback response with one action", "a short review note and useful phrases"),
            ("Can acknowledge strengths, address specific comments, and propose a concrete revision.", "a professional feedback exchange with a revision plan", "the review note and task criteria only"),
            ("Can evaluate feedback, distinguish minor from substantive points, and negotiate a revision scope.", "a calibrated response that accepts some and questions other feedback points", "the review document and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="work.handle_a_meeting",
        title="Participate in a short work meeting",
        context_family="work",
        premise="A realistic practice meeting about a recognizable project supplies the agenda, notes, and action items needed to contribute, summarize, or follow up without impersonating a real organization.",
        learner_role="team member contributing a point, summarizing a decision, or confirming an action",
        partner_roles=("colleague", "team lead", "external partner"),
        setting_slots=("agenda item", "discussion evidence", "decision or disputed point", "action item and constraint"),
        text_types=("meeting agenda", "meeting notes", "follow-up message"),
        compatible_goal_ids=("workplace_communication", "confident_conversation", "academic_study"),
        compatible_interest_ids=("business", "technology", "education", "science"),
        outcomes=_outcomes(
            ("Can find a decision and an action item from a simple meeting note.", "a short action confirmation", "a labelled notes card and sentence frames"),
            ("Can summarize one meeting decision and say who does what next.", "a brief meeting summary and action note", "a clear agenda and phrase bank"),
            ("Can summarize the discussion, explain a decision, and confirm responsibilities with deadlines.", "a structured meeting follow-up note", "the meeting notes and task criteria only"),
            ("Can synthesize multiple agenda items, evaluate a disputed point, and draft a clear action plan.", "a comprehensive follow-up that resolves ambiguity", "the complete notes and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="study.use_a_reference_source",
        title="Use a reference source for a task",
        context_family="study",
        premise="An excerpt from a real public reference, glossary, or chart supplies all factual content needed to answer a specific question without requiring outside knowledge.",
        learner_role="learner locating and using information from the supplied source",
        partner_roles=("classmate", "teacher", "study partner"),
        setting_slots=("source type", "specific question", "relevant source sections", "distractor or apparently conflicting detail"),
        text_types=("reference extract", "glossary", "information exchange"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication"),
        compatible_interest_ids=("education", "science", "technology", "history", "culture"),
        outcomes=_outcomes(
            ("Can find one specific fact in a short labelled reference extract.", "a short factual answer with a source location", "a highlighted extract and fixed answer frames"),
            ("Can locate and use relevant information from a short reference to answer a simple question.", "a brief answer supported by the source", "a short reference and useful phrases"),
            ("Can select relevant information from a longer extract, paraphrase it, and apply it to the task question.", "an accurate task answer with a source reference", "the reference and task criteria"),
            ("Can synthesize information from multiple sections, resolve apparent contradictions, and construct a supported answer.", "a nuanced answer that handles contradictions", "the complete source and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="study.give_a_short_presentation",
        title="Give a short presentation",
        context_family="study",
        premise="A real topic and supplied source notes give the learner all content needed for a short structured spoken or written presentation.",
        learner_role="student giving a clear, organised short presentation on a real topic",
        partner_roles=("classmate", "teacher", "audience member"),
        setting_slots=("real source-grounded topic", "key points", "one supporting detail each", "closing statement and likely audience question"),
        text_types=("presentation notes", "slide summary", "audience Q&A"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication", "confident_conversation"),
        compatible_interest_ids=("education", "science", "technology", "culture", "history", "business"),
        outcomes=_outcomes(
            ("Can state a topic and mention two key points from supplied notes.", "a very short two-point summary", "labelled notes and fixed opening and closing frames"),
            ("Can give a short organised presentation using supplied notes with an opening, two points, and a close.", "a brief structured presentation", "structured notes and a phrase bank"),
            ("Can present a topic clearly with an introduction, developed supporting points, and a conclusion.", "a coherent short presentation with evidence", "the notes and presentation criteria"),
            ("Can deliver a structured presentation, anticipate a challenging question, and respond constructively.", "a complete presentation with a prepared Q&A response", "the topic brief and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="technology.communicate_a_digital_process",
        title="Explain a digital process",
        context_family="technology",
        premise="A real, version-named digital tool is explained through an officially grounded step-by-step workflow, including a decision branch and a recoverable common failure.",
        learner_role="user explaining the process to someone who has not done it before",
        partner_roles=("colleague", "friend", "help-desk contact"),
        setting_slots=("real version-named tool or process", "documented steps", "decision branch", "common failure and recovery"),
        text_types=("process guide", "interface description", "explanation dialogue"),
        compatible_goal_ids=("workplace_communication", "confident_conversation", "academic_study"),
        compatible_interest_ids=("technology", "business", "education", "daily_life"),
        outcomes=_outcomes(
            ("Can identify the first and last step of a simple documented process.", "a short first-and-last-step summary", "a numbered steps card and fixed sequence frames"),
            ("Can explain the key steps of a familiar process using simple sequence language.", "a brief step-by-step explanation", "the process guide and phrase bank"),
            ("Can explain a digital process clearly, flag the decision point, and warn about the common mistake.", "a complete process explanation with a caution", "the documented workflow and outcome criteria"),
            ("Can explain a multi-path process, justify a decision at a branch point, and troubleshoot an anticipated failure.", "a precise explanation covering the decision branch and recovery", "the complete workflow and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="technology.evaluate_digital_information",
        title="Evaluate a piece of digital information",
        context_family="technology",
        premise="A real published page or a clearly labelled practice post about a real topic contains a claim evaluated only from supplied context, source details, and explicitly stated supporting and cautionary signals.",
        learner_role="user deciding whether the information is reliable and explaining why",
        partner_roles=("friend", "colleague", "classmate"),
        setting_slots=("real published or clearly simulated content piece", "source details", "one supporting signal", "one cautionary or conflicting signal"),
        text_types=("online post", "notification", "evaluation dialogue"),
        compatible_goal_ids=("academic_study", "exam_preparation", "confident_conversation", "workplace_communication"),
        compatible_interest_ids=("technology", "education", "science", "daily_life"),
        outcomes=_outcomes(
            ("Can identify one labelled detail that supports or weakens confidence in a simple claim.", "a short confidence judgement", "labelled source signals and fixed judgement frames"),
            ("Can describe one supporting and one cautionary signal in a short content piece.", "a brief reliability note with two signals", "the content card and useful phrases"),
            ("Can evaluate the reliability of a content piece using supplied signals and give a supported judgement.", "a clear reliability evaluation with evidence", "the supplied content and criteria"),
            ("Can weigh conflicting signals, qualify a reliability judgement, and suggest a proportionate response.", "a nuanced reliability assessment with a recommended action", "the complete supplied piece and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="entertainment.plan_a_fictional_event",
        title="Coordinate an entertainment event",
        context_family="entertainment",
        premise="A community group has chosen an event built around a real work, artist, game, or performance format and must assign responsibilities, prepare resources, communicate access needs, and handle one simulated logistical risk.",
        learner_role="event organizer coordinating people, resources, and a contingency",
        partner_roles=("friend", "club member", "volunteer organizer"),
        setting_slots=("fixed event format", "participant or access needs", "roles and resources", "logistical risk and contingency"),
        text_types=("event brief", "responsibility checklist", "organizer dialogue"),
        compatible_goal_ids=("confident_conversation", "workplace_communication", "academic_study"),
        compatible_interest_ids=("entertainment", "daily_life", "culture", "music", "sports"),
        outcomes=_outcomes(
            ("Can identify one event task and say who will do it.", "a short responsibility confirmation", "a labelled checklist and fixed coordination frames"),
            ("Can confirm a role, a needed resource, and one practical event detail.", "a brief organizer message", "the event brief and a phrase bank"),
            ("Can coordinate roles and resources, address an access need, and propose a response to the logistical risk.", "a connected coordination note with a practical contingency", "the event brief and outcome criteria"),
            ("Can negotiate responsibilities, access needs, and logistics while justifying a workable contingency.", "a detailed event-operations plan with assigned responsibilities", "the complete event evidence and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="entertainment.review_a_fictional_product",
        title="Review a real creative work",
        context_family="entertainment",
        premise="A real published game, album, film, or show is presented through a source-grounded feature or storyline summary and supplied reactions that are either sourced or clearly identified as practice opinions.",
        learner_role="reviewer using only supplied details to write or discuss a fair evaluation",
        partner_roles=("friend", "online reviewer", "classmate"),
        setting_slots=("real published creative work", "source-grounded summary", "contrasting sourced or practice reactions", "one supported weak point"),
        text_types=("review draft", "rating card", "review discussion"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("entertainment", "culture", "technology", "music"),
        outcomes=_outcomes(
            ("Can name one good thing and one bad thing about a real creative work from supplied details.", "a short two-point reaction", "a labelled feature card and fixed evaluation frames"),
            ("Can summarize the main features and give a simple overall judgement.", "a brief review with a rating and one reason", "a feature summary and comparison phrases"),
            ("Can write a balanced review using supplied features and audience reactions to support an overall judgement.", "a structured review covering strengths and the weak point", "the feature data and criteria"),
            ("Can craft a nuanced review, weigh contradictory reactions, and qualify an overall recommendation.", "a qualified review that addresses audience disagreement", "the complete supplied work data only"),
        ),
    ),
    ScenarioArchetype(
        id="sports.discuss_performance",
        title="Discuss a documented sports performance",
        context_family="sports",
        premise="A source-grounded record of a real completed athlete or team performance supplies statistics, context, and only genuinely sourced comments needed to analyse what went well and what could improve.",
        learner_role="participant or commentator explaining the performance using only supplied evidence",
        partner_roles=("teammate", "coach", "sports journalist"),
        setting_slots=("real athlete or team", "source-grounded performance stats", "tension between stats and supplied qualitative comments", "area for improvement"),
        text_types=("performance summary", "stat table", "interview extract"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("sports", "entertainment", "education", "daily_life"),
        outcomes=_outcomes(
            ("Can identify one strength and one weakness from a simple performance card.", "a short strength-and-weakness statement", "a labelled stat card and fixed evaluation frames"),
            ("Can describe the main performance and say what went well and what could improve.", "a brief performance summary with two evaluations", "a short stat table and phrase bank"),
            ("Can analyse a performance record, support evaluations with evidence, and suggest a priority improvement.", "a structured evidence-based performance review", "the complete record and task criteria only"),
            ("Can synthesize stats and qualitative comments to deliver a nuanced performance assessment that balances praise with constructive critique.", "a balanced analytical review addressing contradictory evidence", "the full supplied record and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="sports.explain_fictional_rules",
        title="Explain the rules of a real sport or game",
        context_family="sports",
        premise="A real sport or game has an official or authoritative rulebook extract supplying all scoring, play, and boundary rules needed without requiring prior knowledge.",
        learner_role="participant explaining the rules clearly to a newcomer",
        partner_roles=("new player", "curious friend", "referee"),
        setting_slots=("real sport or game", "officially grounded core rules", "scoring system", "tricky rule and supplied disputed edge case"),
        text_types=("rulebook extract", "rule explanation dialogue", "referee note"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("sports", "education", "entertainment", "daily_life"),
        outcomes=_outcomes(
            ("Can identify the main goal of the real sport or game and one basic rule.", "a short goal-and-rule statement", "a labelled rulebook card and sentence frames"),
            ("Can explain the core rules and scoring of the real sport or game in simple terms.", "a brief clear rules explanation", "the rulebook extract and a phrase bank"),
            ("Can explain the full rules, scoring, and the tricky rule clearly to someone new.", "a complete rules explanation covering all key points", "the rulebook and outcome criteria"),
            ("Can explain the complete rules, handle a rule dispute using the text, and negotiate an edge case.", "a complete rules explanation that resolves the edge case", "the full rulebook extract and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="culture.interpret_a_cultural_practice",
        title="Interpret a cultural practice",
        context_family="culture",
        premise="A real cultural practice is presented through respectful public documentation or community-authored material covering its context, elements, documented change, and a sourced misconception without exposing restricted or sacred knowledge.",
        learner_role="person explaining the practice and its significance to an outsider",
        partner_roles=("visitor", "curious classmate", "community member"),
        setting_slots=("real publicly documented cultural practice", "community-grounded context and significance", "public steps or elements", "documented change and sourced misconception"),
        text_types=("community guide", "cultural note", "explanation dialogue"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation", "travel_independence"),
        compatible_interest_ids=("culture", "education", "travel", "history", "entertainment"),
        outcomes=_outcomes(
            ("Can name the practice and say one thing it involves.", "a short practice identification", "a labelled culture card and sentence frames"),
            ("Can describe the main public elements of the real practice and say why it matters.", "a brief practice description with a significance statement", "a short community-grounded guide and useful phrases"),
            ("Can explain the context, public elements, and significance of the real practice clearly to an outsider.", "a connected cultural explanation", "the supplied guide and outcome criteria"),
            ("Can explain the practice, use supplied history to address a sourced misconception, and discuss documented change over time.", "a nuanced cultural explanation that corrects the supplied misconception", "the complete community-grounded guide and criteria only"),
        ),
    ),
)
