"""Core reviewed scenarios for the deterministic mission catalog."""

from __future__ import annotations

from .mission_catalog_models import CEFR_LEVELS, LevelOutcome, ScenarioArchetype


def _outcomes(a1: tuple[str, str, str], a2: tuple[str, str, str], b1: tuple[str, str, str], b2: tuple[str, str, str]) -> tuple[LevelOutcome, ...]:
    return tuple(LevelOutcome(level, can_do, product, support) for level, (can_do, product, support) in zip(CEFR_LEVELS, (a1, a2, b1, b2), strict=True))


CORE_SCENARIO_ARCHETYPES: tuple[ScenarioArchetype, ...] = (
    ScenarioArchetype(
        id="everyday.make_shared_plan",
        title="Make a shared plan",
        context_family="everyday",
        premise="Two or more people need to agree on the time, place, and practical details of an activity at a recognizable real-world venue or community setting.",
        learner_role="participant helping the group reach a workable plan",
        partner_roles=("friend", "neighbor", "club member"),
        setting_slots=("activity", "time options", "place options", "one practical constraint"),
        text_types=("message exchange", "short notice", "simple schedule"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "workplace_communication", "academic_study"),
        compatible_interest_ids=("daily_life", "travel", "culture", "sports", "entertainment"),
        outcomes=_outcomes(
            ("Can choose a time and place for a familiar activity using short expressions.", "a short accepted plan", "visible time/place options and a phrase bank"),
            ("Can exchange simple suggestions and agree on practical arrangements.", "a brief message confirming arrangements", "a short model and optional useful phrases"),
            ("Can compare practical constraints and negotiate a workable shared plan.", "a connected proposal with a reason and confirmation", "a task frame with no model answer"),
            ("Can negotiate arrangements, qualify preferences, and resolve competing constraints.", "a clear agreement that acknowledges alternatives", "outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="everyday.resolve_service_problem",
        title="Resolve an everyday service problem",
        context_family="everyday",
        premise="A realistic practice case about an actual kind of local service contains a clear routine mistake that can be resolved from the supplied record without attributing it to a real provider.",
        learner_role="customer explaining the issue and requesting a proportionate solution",
        partner_roles=("service assistant", "receptionist", "support representative"),
        setting_slots=("service type", "expected result", "observed problem", "available remedies"),
        text_types=("receipt", "appointment note", "service dialogue"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "workplace_communication", "exam_preparation"),
        compatible_interest_ids=("daily_life", "travel", "business", "technology"),
        outcomes=_outcomes(
            ("Can state a simple service problem and ask for help.", "a short help request", "a labelled record and fixed request frames"),
            ("Can explain a routine problem and request one clear remedy.", "a brief problem-and-request message", "a phrase bank and explicit remedy options"),
            ("Can describe what went wrong, refer to evidence, and agree on a practical remedy.", "a supported resolution request", "the service record and task criteria"),
            ("Can present a service complaint precisely, evaluate remedies, and negotiate a fair outcome.", "a proportionate negotiated resolution", "the evidence record and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="travel.compare_journey_options",
        title="Choose a journey option",
        context_family="travel",
        premise="A route between real places is paired with a clearly labelled practice timetable containing several internally consistent options, costs, and constraints.",
        learner_role="traveler choosing and explaining the most suitable option",
        partner_roles=("travel companion", "booking assistant", "host"),
        setting_slots=("real origin and destination", "practice option table", "traveler priorities", "constraint"),
        text_types=("timetable", "booking summary", "travel dialogue"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("travel", "culture", "daily_life"),
        outcomes=_outcomes(
            ("Can identify a suitable journey time and price from a simple list.", "one selected option with a short reason", "icons, labels, and two options"),
            ("Can compare familiar journey options and state a preference.", "a short booking choice", "a clear table and comparison phrases"),
            ("Can evaluate journey options against stated priorities and recommend one.", "a recommendation supported by relevant details", "an option table and task criteria"),
            ("Can weigh competing journey constraints and justify a qualified recommendation.", "a reasoned choice that addresses a trade-off", "evidence table only"),
        ),
    ),
    ScenarioArchetype(
        id="travel.handle_changed_arrangement",
        title="Handle a changed travel arrangement",
        context_family="travel",
        premise="A simulated booking or meeting connected to a real destination changes, and the learner must use the supplied notice to choose a next step.",
        learner_role="traveler responding constructively to the change",
        partner_roles=("travel assistant", "host", "travel companion"),
        setting_slots=("original arrangement", "change notice", "available alternatives", "priority"),
        text_types=("change notification", "announcement", "support exchange"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "workplace_communication"),
        compatible_interest_ids=("travel", "culture", "daily_life"),
        outcomes=_outcomes(
            ("Can understand the new time or place and choose a stated alternative.", "a simple confirmed alternative", "highlighted before/after details"),
            ("Can understand a routine change and ask or answer a practical follow-up question.", "a short revised arrangement", "a clear notice and question frames"),
            ("Can explain the effect of a change and arrange a suitable alternative.", "a connected response with a practical next step", "the notice and available alternatives"),
            ("Can assess the consequences of a changed arrangement and negotiate an effective alternative.", "a qualified recovery plan", "source details and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="work.coordinate_shared_task",
        title="Coordinate a shared task",
        context_family="work",
        premise="A realistic team working on a recognizable project type must divide a familiar task, confirm responsibilities, and meet a simulated internal deadline.",
        learner_role="team member coordinating a clear part of the work",
        partner_roles=("colleague", "team lead", "project partner"),
        setting_slots=("realistic project outcome", "available people", "responsibilities", "simulated deadline"),
        text_types=("team message", "task list", "brief meeting dialogue"),
        compatible_goal_ids=("workplace_communication", "academic_study", "confident_conversation"),
        compatible_interest_ids=("business", "technology", "education", "science"),
        outcomes=_outcomes(
            ("Can identify a simple task and say who does what.", "a short responsibility statement", "a labelled task list and fixed frames"),
            ("Can exchange simple task information and confirm a deadline.", "a brief coordination message", "a task table and useful phrases"),
            ("Can allocate work, explain a constraint, and confirm shared expectations.", "a clear coordination note", "the task brief and outcome checklist"),
            ("Can coordinate responsibilities, anticipate dependencies, and tactfully resolve a constraint.", "a precise team agreement with contingencies", "brief and success criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="work.report_and_solve_problem",
        title="Report a work problem and propose a next step",
        context_family="work",
        premise="A realistic workplace task has a documented obstacle, and the learner must report it without inventing missing facts or attributing the incident to a real organization.",
        learner_role="team member giving a useful problem update",
        partner_roles=("colleague", "supervisor", "internal support person"),
        setting_slots=("task", "observed obstacle", "known impact", "possible next steps"),
        text_types=("status update", "internal email", "problem-solving dialogue"),
        compatible_goal_ids=("workplace_communication", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("business", "technology", "science", "daily_life"),
        outcomes=_outcomes(
            ("Can state that a familiar task has a problem and ask for help.", "a simple problem update", "labelled problem details and sentence frames"),
            ("Can describe a routine work problem and suggest one practical action.", "a short update and suggestion", "a model structure and supplied facts"),
            ("Can report a problem, explain its likely impact, and recommend a supported next step.", "a structured status update", "the evidence record and criteria"),
            ("Can give a precise problem analysis, qualify uncertainty, and compare proportionate responses.", "a concise decision-oriented update", "documented evidence and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="study.clarify_assignment",
        title="Clarify a learning task",
        context_family="study",
        premise="A realistic course task on a real subject contains supplied requirements, open resources, and one point that needs clarification.",
        learner_role="learner confirming what the task requires",
        partner_roles=("teacher", "classmate", "study adviser"),
        setting_slots=("task type", "requirements", "resource", "ambiguous detail"),
        text_types=("assignment brief", "course message", "clarification exchange"),
        compatible_goal_ids=("academic_study", "exam_preparation", "confident_conversation"),
        compatible_interest_ids=("education", "science", "technology", "culture", "history"),
        outcomes=_outcomes(
            ("Can identify what to do and ask one simple question about a task.", "a short clarification question", "highlighted instruction and a question frame"),
            ("Can understand routine task requirements and confirm a missing detail.", "a brief confirmation exchange", "a structured brief and useful phrases"),
            ("Can summarize task requirements and ask a precise clarification question.", "an accurate task summary and focused question", "the assignment brief and checklist"),
            ("Can interpret detailed requirements, identify ambiguity, and negotiate a clear understanding.", "a concise, justified clarification request", "the complete brief and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="study.plan_group_project",
        title="Plan a group project",
        context_family="study",
        premise="A study group must select a narrow real-world topic, divide source-based work, and agree on a simple process.",
        learner_role="group member contributing to a workable project plan",
        partner_roles=("classmate", "project partner", "course mentor"),
        setting_slots=("project outcome", "real topic options", "roles", "simulated milestones"),
        text_types=("project brief", "planning notes", "group discussion"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication", "confident_conversation"),
        compatible_interest_ids=("education", "science", "technology", "culture", "business", "history"),
        outcomes=_outcomes(
            ("Can choose a simple project topic and say one assigned action.", "a basic topic-and-task plan", "two topic options and fixed planning phrases"),
            ("Can make simple project suggestions and agree on roles and dates.", "a short group plan", "a planning table and phrase bank"),
            ("Can compare project choices, divide responsibilities, and explain the sequence of work.", "a connected project proposal", "a brief and planning criteria"),
            ("Can shape a project plan, justify priorities, and respond constructively to competing proposals.", "a coherent negotiated plan with rationale", "project constraints and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="technology.solve_familiar_issue",
        title="Solve a familiar technology issue",
        context_family="technology",
        premise="A real, widely used device or digital service has a small set of supplied symptoms and troubleshooting options adapted from official guidance.",
        learner_role="user explaining the issue and selecting the safest supported step",
        partner_roles=("support assistant", "colleague", "friend"),
        setting_slots=("real device or service", "symptoms", "officially grounded support note", "possible steps"),
        text_types=("support article", "chat transcript", "status message"),
        compatible_goal_ids=("confident_conversation", "workplace_communication", "academic_study", "exam_preparation"),
        compatible_interest_ids=("technology", "business", "education", "daily_life"),
        outcomes=_outcomes(
            ("Can identify a simple device problem and follow one stated instruction.", "a short problem-and-action response", "pictures or labels and one-step options"),
            ("Can describe a familiar technology problem and choose a documented solution.", "a brief support exchange", "a short support note and phrase bank"),
            ("Can understand a clear problem update and recommend which supplied solution to try first.", "an evidence-based troubleshooting recommendation", "the support evidence and criteria"),
            ("Can evaluate competing explanations, qualify a recommendation, and respond to a counterargument.", "a reasoned troubleshooting plan", "complete supplied case evidence only"),
        ),
    ),
    ScenarioArchetype(
        id="technology.compare_fictional_tools",
        title="Compare real tools for a purpose",
        context_family="technology",
        premise="Several real tools are compared through a supplied, source-grounded feature table whose version and limits are explicit.",
        learner_role="user recommending the best fit for a stated need",
        partner_roles=("friend", "colleague", "study partner"),
        setting_slots=("real tools", "source-grounded feature table", "user need", "trade-off"),
        text_types=("feature table", "short review", "recommendation exchange"),
        compatible_goal_ids=("workplace_communication", "academic_study", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("technology", "business", "education", "science"),
        outcomes=_outcomes(
            ("Can find a named feature and choose a tool for one simple need.", "one choice with a short reason", "two clearly labelled real options"),
            ("Can compare familiar features and state which real tool suits a clear need.", "a brief comparison and recommendation", "a small feature table and comparison frames"),
            ("Can compare supplied features and limitations to recommend an appropriate tool.", "a supported recommendation", "the feature evidence and outcome criteria"),
            ("Can weigh feature trade-offs, challenge assumptions, and qualify a recommendation for a specific user.", "a nuanced evidence-based recommendation", "the complete supplied specification only"),
        ),
    ),
    ScenarioArchetype(
        id="entertainment.choose_shared_experience",
        title="Choose an entertainment experience",
        context_family="entertainment",
        premise="A set of real published films, games, performances, or music works is presented through neutral source-grounded descriptions plus clearly simulated planning details.",
        learner_role="participant helping another person choose a suitable option",
        partner_roles=("friend", "club member", "visitor"),
        setting_slots=("real published options", "preferences", "source-grounded descriptions", "practical constraint"),
        text_types=("programme", "neutral description snippets", "recommendation dialogue"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "exam_preparation"),
        compatible_interest_ids=("entertainment", "culture", "travel", "daily_life", "music"),
        outcomes=_outcomes(
            ("Can identify a type of entertainment and say a simple preference.", "one choice and preference", "pictures or labels and fixed preference frames"),
            ("Can compare simple descriptions and suggest an entertainment option.", "a short suggestion with a reason", "three real options and phrase support"),
            ("Can summarize preferences and recommend a suitable real experience.", "a supported recommendation", "supplied descriptions and criteria"),
            ("Can evaluate contrasting supplied reactions and negotiate a choice that accommodates different tastes.", "a qualified joint recommendation", "the supplied evidence and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="entertainment.discuss_fictional_story",
        title="Discuss a real published story",
        context_family="entertainment",
        premise="A short public-domain or otherwise source-authorized extract from a real published story presents a character choice or interpretation supported entirely by the text.",
        learner_role="reader or viewer explaining an interpretation",
        partner_roles=("friend", "book-club member", "classmate"),
        setting_slots=("source-authorized story extract", "character goal", "key event", "interpretive question"),
        text_types=("story synopsis", "dialogue extract", "discussion exchange"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("entertainment", "culture", "education"),
        outcomes=_outcomes(
            ("Can identify a character, place, and main event in a very short published story extract.", "a short factual response", "a brief illustrated or labelled extract"),
            ("Can describe a main event and give a simple reaction to a published story extract.", "a short summary and opinion", "a short extract and response frames"),
            ("Can summarize a story choice and support an interpretation with textual detail.", "an evidence-linked interpretation", "the extract and question criteria"),
            ("Can compare plausible interpretations and defend a nuanced reading with evidence from the published text.", "a qualified textual interpretation", "the self-contained extract only"),
        ),
    ),
    ScenarioArchetype(
        id="sports.organize_activity",
        title="Organize a sports or fitness activity",
        context_family="sports",
        premise="A community group must choose a real sport or fitness activity, assign simple roles, and account for supplied access or safety guidance.",
        learner_role="participant helping create an inclusive activity plan",
        partner_roles=("teammate", "club organizer", "friend"),
        setting_slots=("real activity options", "participant needs", "venue details", "simulated schedule"),
        text_types=("club notice", "availability table", "planning dialogue"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "workplace_communication"),
        compatible_interest_ids=("sports", "daily_life", "travel"),
        outcomes=_outcomes(
            ("Can choose an activity and state a time or simple need.", "a basic activity arrangement", "labelled options and fixed phrases"),
            ("Can discuss simple activity preferences and agree on familiar arrangements.", "a short inclusive plan", "a schedule and phrase bank"),
            ("Can compare participants' needs and organize a practical group activity.", "a supported activity plan", "supplied needs and outcome criteria"),
            ("Can negotiate an inclusive activity plan, balancing preferences, access, and practical constraints.", "a reasoned plan with accommodations", "all supplied case details only"),
        ),
    ),
    ScenarioArchetype(
        id="sports.recap_fictional_event",
        title="Explain a documented sports event",
        context_family="sports",
        premise="A source-grounded record of a real completed sports event supplies the actions, result, timing, and any attributed comments needed for a recap.",
        learner_role="participant or reporter explaining what happened and why it mattered",
        partner_roles=("friend", "club member", "interviewer"),
        setting_slots=("real completed event", "source-grounded timeline", "result", "attributed comments when supplied"),
        text_types=("event timeline", "match report extract", "interview extract"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("sports", "entertainment", "daily_life"),
        outcomes=_outcomes(
            ("Can identify who took part and the result of a documented event.", "a simple result statement", "a labelled event card"),
            ("Can give a short sequence of key events and a simple reaction.", "a brief ordered recap", "a clear timeline and sequencing phrases"),
            ("Can summarize a documented event, connect cause and result, and report a supplied participant view.", "a connected evidence-based recap", "the event record and criteria"),
            ("Can synthesize a documented event record, distinguish report from interpretation, and qualify an evaluation.", "a balanced analytical recap", "the complete supplied record only"),
        ),
    ),
    ScenarioArchetype(
        id="culture.plan_fictional_visit",
        title="Plan a visit to a real cultural place",
        context_family="culture",
        premise="A real museum, library, heritage place, or cultural institution is paired with stable source-grounded descriptions and clearly dated or simulated visit options.",
        learner_role="visitor planning a suitable experience",
        partner_roles=("friend", "visitor assistant", "group member"),
        setting_slots=("real cultural place", "dated or simulated programme", "visitor priorities", "supplied access information"),
        text_types=("visitor guide", "programme", "planning exchange"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("culture", "travel", "entertainment", "education", "music"),
        outcomes=_outcomes(
            ("Can find a time, place, and activity in a simple visitor guide.", "a simple visit choice", "labels, icons, and two options"),
            ("Can use a short guide to suggest a suitable cultural activity.", "a brief visit suggestion", "a small programme and useful phrases"),
            ("Can compare programme details and recommend a visit that meets stated priorities.", "a supported itinerary recommendation", "the supplied guide and criteria"),
            ("Can synthesize programme and access information to negotiate a well-justified cultural itinerary.", "a qualified itinerary with trade-offs", "the complete supplied programme only"),
        ),
    ),
    ScenarioArchetype(
        id="science.explain_supplied_observation",
        title="Explain a supplied observation",
        context_family="science",
        premise="A real natural phenomenon or reproducible classroom investigation is presented through a complete supplied observation record without requiring specialist knowledge.",
        learner_role="learner describing the pattern and its supported explanation",
        partner_roles=("study partner", "teacher", "project teammate"),
        setting_slots=("real phenomenon or investigation", "observation table", "comparison", "supported explanation options"),
        text_types=("observation log", "simple chart description", "discussion exchange"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication", "confident_conversation"),
        compatible_interest_ids=("science", "education", "technology", "daily_life"),
        outcomes=_outcomes(
            ("Can identify a simple change or difference in a supplied observation.", "a short observation statement", "labels, visuals, and fixed comparison frames"),
            ("Can describe a simple pattern and connect it to a supplied reason.", "a brief pattern-and-reason explanation", "a small observation table and phrase bank"),
            ("Can summarize a supplied pattern, distinguish observation from explanation, and support a conclusion.", "an evidence-linked explanation", "the complete accessible record and criteria"),
            ("Can evaluate the limits of a supplied observation and present a qualified evidence-based explanation.", "a cautious analytical explanation", "the self-contained record and outcome criteria only"),
        ),
    ),
)
