"""Reviewed scenario archetypes used by the deterministic mission catalog."""

from __future__ import annotations

from .mission_catalog_models import CEFR_LEVELS, LevelOutcome, ScenarioArchetype


def _outcomes(
    a1: tuple[str, str, str],
    a2: tuple[str, str, str],
    b1: tuple[str, str, str],
    b2: tuple[str, str, str],
) -> tuple[LevelOutcome, ...]:
    return tuple(
        LevelOutcome(level, can_do, product, support)
        for level, (can_do, product, support) in zip(CEFR_LEVELS, (a1, a2, b1, b2), strict=True)
    )


SCENARIO_ARCHETYPES: tuple[ScenarioArchetype, ...] = (
    ScenarioArchetype(
        id="everyday.make_shared_plan",
        title="Make a shared plan",
        context_family="everyday",
        premise="Two or more fictional people need to agree on the time, place, and practical details of a familiar activity.",
        learner_role="participant helping the group reach a workable plan",
        partner_roles=("friend", "neighbor", "club member"),
        setting_slots=("activity", "time options", "place options", "one practical constraint"),
        text_types=("message exchange", "short notice", "simple schedule"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "workplace_communication", "academic_study"),
        compatible_interest_ids=("daily_life", "travel", "culture", "sports", "entertainment"),
        outcomes=_outcomes(
            ("Can choose a time and place for a familiar activity using short expressions.", "a short accepted plan", "visible time/place options and a phrase bank"),
            ("Can exchange simple suggestions and agree on practical arrangements.", "a brief message confirming arrangements", "a short model and optional useful phrases"),
            ("Can compare practical constraints and negotiate a workable shared plan.", "a connected proposal with a reason and confirmation", "a task frame with no model answer"),
            ("Can negotiate arrangements, qualify preferences, and resolve competing constraints.", "a clear agreement that acknowledges alternatives", "outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="everyday.resolve_service_problem",
        title="Resolve an everyday service problem",
        context_family="everyday",
        premise="A fictional local service has made a clear, routine mistake that can be resolved from the supplied record.",
        learner_role="customer explaining the issue and requesting a proportionate solution",
        partner_roles=("service assistant", "receptionist", "support representative"),
        setting_slots=("service type", "expected result", "observed problem", "available remedies"),
        text_types=("receipt", "appointment note", "service dialogue"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "workplace_communication", "exam_preparation"),
        compatible_interest_ids=("daily_life", "travel", "business", "technology"),
        outcomes=_outcomes(
            ("Can state a simple service problem and ask for help.", "a short help request", "a labelled record and fixed request frames"),
            ("Can explain a routine problem and request one clear remedy.", "a brief problem-and-request message", "a phrase bank and explicit remedy options"),
            ("Can describe what went wrong, refer to evidence, and agree on a practical remedy.", "a supported resolution request", "the service record and task criteria"),
            ("Can present a service complaint precisely, evaluate remedies, and negotiate a fair outcome.", "a proportionate negotiated resolution", "the evidence record and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="travel.compare_journey_options",
        title="Choose a journey option",
        context_family="travel",
        premise="A fictional journey offers several internally consistent options with different times, costs, and constraints.",
        learner_role="traveler choosing and explaining the most suitable option",
        partner_roles=("travel companion", "booking assistant", "host"),
        setting_slots=("fictional destination", "option table", "traveler priorities", "constraint"),
        text_types=("timetable", "booking summary", "travel dialogue"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("travel", "culture", "daily_life"),
        outcomes=_outcomes(
            ("Can identify a suitable journey time and price from a simple list.", "one selected option with a short reason", "icons, labels, and two options"),
            ("Can compare familiar journey options and state a preference.", "a short booking choice", "a clear table and comparison phrases"),
            ("Can evaluate journey options against stated priorities and recommend one.", "a recommendation supported by relevant details", "an option table and task criteria"),
            ("Can weigh competing journey constraints and justify a qualified recommendation.", "a reasoned choice that addresses a trade-off", "evidence table only"),
        ),
    ),
    ScenarioArchetype(
        id="travel.handle_changed_arrangement",
        title="Handle a changed travel arrangement",
        context_family="travel",
        premise="A fictional booking or meeting arrangement changes and the learner must understand the update and choose a next step.",
        learner_role="traveler responding constructively to the change",
        partner_roles=("travel assistant", "host", "travel companion"),
        setting_slots=("original arrangement", "change notice", "available alternatives", "priority"),
        text_types=("change notification", "announcement", "support exchange"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "workplace_communication"),
        compatible_interest_ids=("travel", "culture", "daily_life"),
        outcomes=_outcomes(
            ("Can understand the new time or place and choose a stated alternative.", "a simple confirmed alternative", "highlighted before/after details"),
            ("Can understand a routine change and ask or answer a practical follow-up question.", "a short revised arrangement", "a clear notice and question frames"),
            ("Can explain the effect of a change and arrange a suitable alternative.", "a connected response with a practical next step", "the notice and available alternatives"),
            ("Can assess the consequences of a changed arrangement and negotiate an effective alternative.", "a qualified recovery plan", "source details and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="work.coordinate_shared_task",
        title="Coordinate a shared task",
        context_family="work",
        premise="A fictional team must divide a familiar task, confirm responsibilities, and meet an internal deadline.",
        learner_role="team member coordinating a clear part of the work",
        partner_roles=("colleague", "team lead", "project partner"),
        setting_slots=("task outcome", "available people", "responsibilities", "fictional deadline"),
        text_types=("team message", "task list", "brief meeting dialogue"),
        compatible_goal_ids=("workplace_communication", "academic_study", "confident_conversation"),
        compatible_interest_ids=("business", "technology", "education", "science"),
        outcomes=_outcomes(
            ("Can identify a simple task and say who does what.", "a short responsibility statement", "a labelled task list and fixed frames"),
            ("Can exchange simple task information and confirm a deadline.", "a brief coordination message", "a task table and useful phrases"),
            ("Can allocate work, explain a constraint, and confirm shared expectations.", "a clear coordination note", "the task brief and outcome checklist"),
            ("Can coordinate responsibilities, anticipate dependencies, and tactfully resolve a constraint.", "a precise team agreement with contingencies", "brief and success criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="work.report_and_solve_problem",
        title="Report a work problem and propose a next step",
        context_family="work",
        premise="A fictional routine task has a documented obstacle, and the learner must report it without inventing missing facts.",
        learner_role="team member giving a useful problem update",
        partner_roles=("colleague", "supervisor", "internal support person"),
        setting_slots=("task", "observed obstacle", "known impact", "possible next steps"),
        text_types=("status update", "internal email", "problem-solving dialogue"),
        compatible_goal_ids=("workplace_communication", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("business", "technology", "science", "daily_life"),
        outcomes=_outcomes(
            ("Can state that a familiar task has a problem and ask for help.", "a simple problem update", "labelled problem details and sentence frames"),
            ("Can describe a routine work problem and suggest one practical action.", "a short update and suggestion", "a model structure and supplied facts"),
            ("Can report a problem, explain its likely impact, and recommend a supported next step.", "a structured status update", "the evidence record and criteria"),
            ("Can give a precise problem analysis, qualify uncertainty, and compare proportionate responses.", "a concise decision-oriented update", "documented evidence and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="study.clarify_assignment",
        title="Clarify a learning task",
        context_family="study",
        premise="A fictional course task contains requirements, resources, and one point that needs clarification.",
        learner_role="learner confirming what the task requires",
        partner_roles=("teacher", "classmate", "study adviser"),
        setting_slots=("task type", "requirements", "resource", "ambiguous detail"),
        text_types=("assignment brief", "course message", "clarification exchange"),
        compatible_goal_ids=("academic_study", "exam_preparation", "confident_conversation"),
        compatible_interest_ids=("education", "science", "technology", "culture", "history"),
        outcomes=_outcomes(
            ("Can identify what to do and ask one simple question about a task.", "a short clarification question", "highlighted instruction and a question frame"),
            ("Can understand routine task requirements and confirm a missing detail.", "a brief confirmation exchange", "a structured brief and useful phrases"),
            ("Can summarize task requirements and ask a precise clarification question.", "an accurate task summary and focused question", "the assignment brief and checklist"),
            ("Can interpret detailed requirements, identify ambiguity, and negotiate a clear understanding.", "a concise, justified clarification request", "the complete brief and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="study.plan_group_project",
        title="Plan a group project",
        context_family="study",
        premise="A fictional study group must select a narrow topic, divide work, and agree on a simple process.",
        learner_role="group member contributing to a workable project plan",
        partner_roles=("classmate", "project partner", "course mentor"),
        setting_slots=("project outcome", "topic options", "roles", "fictional milestones"),
        text_types=("project brief", "planning notes", "group discussion"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication", "confident_conversation"),
        compatible_interest_ids=("education", "science", "technology", "culture", "business", "history"),
        outcomes=_outcomes(
            ("Can choose a simple project topic and say one assigned action.", "a basic topic-and-task plan", "two topic options and fixed planning phrases"),
            ("Can make simple project suggestions and agree on roles and dates.", "a short group plan", "a planning table and phrase bank"),
            ("Can compare project choices, divide responsibilities, and explain the sequence of work.", "a connected project proposal", "a brief and planning criteria"),
            ("Can shape a project plan, justify priorities, and respond constructively to competing proposals.", "a coherent negotiated plan with rationale", "project constraints and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="technology.solve_familiar_issue",
        title="Solve a familiar technology issue",
        context_family="technology",
        premise="A fictional device or service has a small set of supplied symptoms and documented troubleshooting options.",
        learner_role="user explaining the issue and selecting the safest supported step",
        partner_roles=("support assistant", "colleague", "friend"),
        setting_slots=("fictional device", "symptoms", "support note", "possible steps"),
        text_types=("support article", "chat transcript", "status message"),
        compatible_goal_ids=("confident_conversation", "workplace_communication", "academic_study", "exam_preparation"),
        compatible_interest_ids=("technology", "business", "education", "daily_life"),
        outcomes=_outcomes(
            ("Can identify a simple device problem and follow one stated instruction.", "a short problem-and-action response", "pictures or labels and one-step options"),
            ("Can describe a familiar technology problem and choose a documented solution.", "a brief support exchange", "a short support note and phrase bank"),
            ("Can understand a clear problem update and recommend which supplied solution to try first.", "an evidence-based troubleshooting recommendation", "the support evidence and criteria"),
            ("Can evaluate competing explanations, qualify a recommendation, and respond to a counterargument.", "a reasoned troubleshooting plan", "complete fictional case evidence only"),
        ),
    ),
    ScenarioArchetype(
        id="technology.compare_fictional_tools",
        title="Compare fictional tools for a purpose",
        context_family="technology",
        premise="Several fictional tools have explicitly supplied features, limitations, and use conditions.",
        learner_role="user recommending the best fit for a stated need",
        partner_roles=("friend", "colleague", "study partner"),
        setting_slots=("fictional tools", "feature table", "user need", "trade-off"),
        text_types=("feature table", "short review", "recommendation exchange"),
        compatible_goal_ids=("workplace_communication", "academic_study", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("technology", "business", "education", "science"),
        outcomes=_outcomes(
            ("Can find a named feature and choose a tool for one simple need.", "one choice with a short reason", "two clearly labelled fictional options"),
            ("Can compare familiar features and state which fictional tool suits a clear need.", "a brief comparison and recommendation", "a small feature table and comparison frames"),
            ("Can compare supplied features and limitations to recommend an appropriate tool.", "a supported recommendation", "the feature evidence and outcome criteria"),
            ("Can weigh feature trade-offs, challenge assumptions, and qualify a recommendation for a specific user.", "a nuanced evidence-based recommendation", "the complete fictional specification only"),
        ),
    ),
    ScenarioArchetype(
        id="entertainment.choose_shared_experience",
        title="Choose an entertainment experience",
        context_family="entertainment",
        premise="A fictional set of films, games, performances, or music events offers contrasting genres and practical details.",
        learner_role="participant helping another person choose a suitable option",
        partner_roles=("friend", "club member", "visitor"),
        setting_slots=("fictional options", "preferences", "content descriptions", "practical constraint"),
        text_types=("programme", "fictional review snippets", "recommendation dialogue"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "exam_preparation"),
        compatible_interest_ids=("entertainment", "culture", "travel", "daily_life", "music"),
        outcomes=_outcomes(
            ("Can identify a type of entertainment and say a simple preference.", "one choice and preference", "pictures or labels and fixed preference frames"),
            ("Can compare simple descriptions and suggest an entertainment option.", "a short suggestion with a reason", "three fictional options and phrase support"),
            ("Can summarize preferences and recommend a suitable fictional experience.", "a supported recommendation", "supplied descriptions and criteria"),
            ("Can evaluate contrasting fictional reviews and negotiate a choice that accommodates different tastes.", "a qualified joint recommendation", "the review evidence and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="entertainment.discuss_fictional_story",
        title="Discuss a fictional story",
        context_family="entertainment",
        premise="A self-contained fictional story extract presents a character choice or interpretation supported entirely by the text.",
        learner_role="reader or viewer explaining an interpretation",
        partner_roles=("friend", "book-club member", "classmate"),
        setting_slots=("fictional extract", "character goal", "key event", "interpretive question"),
        text_types=("story synopsis", "dialogue extract", "discussion exchange"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("entertainment", "culture", "education"),
        outcomes=_outcomes(
            ("Can identify a character, place, and main event in a very short fictional story.", "a short factual response", "a brief illustrated or labelled extract"),
            ("Can describe a main event and give a simple reaction to a fictional story.", "a short summary and opinion", "a short extract and response frames"),
            ("Can summarize a fictional story choice and support an interpretation with textual detail.", "an evidence-linked interpretation", "the extract and question criteria"),
            ("Can compare plausible interpretations and defend a nuanced reading with evidence from the fictional text.", "a qualified textual interpretation", "the self-contained extract only"),
        ),
    ),
    ScenarioArchetype(
        id="sports.organize_activity",
        title="Organize a sports or fitness activity",
        context_family="sports",
        premise="A fictional group must choose a suitable activity, assign simple roles, and account for stated access or safety needs.",
        learner_role="participant helping create an inclusive activity plan",
        partner_roles=("teammate", "club organizer", "friend"),
        setting_slots=("activity options", "participant needs", "venue details", "fictional schedule"),
        text_types=("club notice", "availability table", "planning dialogue"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "workplace_communication"),
        compatible_interest_ids=("sports", "daily_life", "travel"),
        outcomes=_outcomes(
            ("Can choose an activity and state a time or simple need.", "a basic activity arrangement", "labelled options and fixed phrases"),
            ("Can discuss simple activity preferences and agree on familiar arrangements.", "a short inclusive plan", "a schedule and phrase bank"),
            ("Can compare participants' needs and organize a practical group activity.", "a supported activity plan", "supplied needs and outcome criteria"),
            ("Can negotiate an inclusive activity plan, balancing preferences, access, and practical constraints.", "a reasoned plan with accommodations", "all fictional case details only"),
        ),
    ),
    ScenarioArchetype(
        id="sports.recap_fictional_event",
        title="Explain a fictional sports event",
        context_family="sports",
        premise="A fictional event record supplies all actions, results, participant comments, and timing needed for a recap.",
        learner_role="participant or reporter explaining what happened and why it mattered",
        partner_roles=("friend", "club member", "fictional interviewer"),
        setting_slots=("fictional event", "event timeline", "result", "participant comments"),
        text_types=("event timeline", "fictional match report", "interview extract"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("sports", "entertainment", "daily_life"),
        outcomes=_outcomes(
            ("Can identify who took part and the result of a short fictional event.", "a simple result statement", "a labelled event card"),
            ("Can give a short sequence of key events and a simple reaction.", "a brief ordered recap", "a clear timeline and sequencing phrases"),
            ("Can summarize a fictional event, connect cause and result, and report a participant view.", "a connected evidence-based recap", "the event record and criteria"),
            ("Can synthesize a fictional event record, distinguish report from interpretation, and qualify an evaluation.", "a balanced analytical recap", "the complete supplied record only"),
        ),
    ),
    ScenarioArchetype(
        id="culture.plan_fictional_visit",
        title="Plan a fictional cultural visit",
        context_family="culture",
        premise="A fictional venue or community programme supplies stable descriptions, opening slots, access information, and event options.",
        learner_role="visitor planning a suitable experience",
        partner_roles=("friend", "visitor assistant", "group member"),
        setting_slots=("fictional venue", "programme", "visitor priorities", "access constraint"),
        text_types=("visitor guide", "programme", "planning exchange"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("culture", "travel", "entertainment", "education", "music"),
        outcomes=_outcomes(
            ("Can find a time, place, and activity in a simple fictional visitor guide.", "a simple visit choice", "labels, icons, and two options"),
            ("Can use a short guide to suggest a suitable cultural activity.", "a brief visit suggestion", "a small programme and useful phrases"),
            ("Can compare programme details and recommend a visit that meets stated priorities.", "a supported itinerary recommendation", "the fictional guide and criteria"),
            ("Can synthesize programme and access information to negotiate a well-justified cultural itinerary.", "a qualified itinerary with trade-offs", "the complete fictional programme only"),
        ),
    ),
    ScenarioArchetype(
        id="science.explain_supplied_observation",
        title="Explain a supplied observation",
        context_family="science",
        premise="A fictional classroom or community investigation provides a complete observation record without requiring specialist knowledge.",
        learner_role="learner describing the pattern and its supported explanation",
        partner_roles=("study partner", "teacher", "project teammate"),
        setting_slots=("accessible topic", "fictional observation table", "comparison", "supported explanation options"),
        text_types=("observation log", "simple chart description", "discussion exchange"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication", "confident_conversation"),
        compatible_interest_ids=("science", "education", "technology", "daily_life"),
        outcomes=_outcomes(
            ("Can identify a simple change or difference in a supplied observation.", "a short observation statement", "labels, visuals, and fixed comparison frames"),
            ("Can describe a simple pattern and connect it to a supplied reason.", "a brief pattern-and-reason explanation", "a small observation table and phrase bank"),
            ("Can summarize a supplied pattern, distinguish observation from explanation, and support a conclusion.", "an evidence-linked explanation", "the complete accessible record and criteria"),
            ("Can evaluate the limits of a supplied observation and present a qualified evidence-based explanation.", "a cautious analytical explanation", "the self-contained record and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="science.present_comparison",
        title="Present a comparison from supplied data",
        context_family="science",
        premise="A fictional dataset or experiment supplies two sets of measurements side by side with all numbers needed to draw a conclusion.",
        learner_role="learner presenting what the comparison shows and what it implies",
        partner_roles=("classmate", "teacher", "study partner"),
        setting_slots=("accessible topic", "fictional dataset", "key difference", "supported implication"),
        text_types=("comparison table", "bar chart description", "presentation dialogue"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication"),
        compatible_interest_ids=("science", "education", "technology", "sports"),
        outcomes=_outcomes(
            ("Can identify which group is larger or smaller in a simple fictional table.", "a short comparison statement", "labelled columns and fixed comparison frames"),
            ("Can describe the key difference between two groups and say what it shows.", "a brief comparison with a simple conclusion", "a small table and useful phrases"),
            ("Can present the main finding from a supplied dataset and connect it to a plausible implication.", "a clear evidence-linked comparison", "the complete dataset and criteria"),
            ("Can interpret ambiguous data, qualify a conclusion, and anticipate a counterargument.", "a cautious qualified comparison with a rebuttal", "the self-contained dataset only"),
        ),
    ),
    ScenarioArchetype(
        id="culture.respond_to_shared_story",
        title="Share a response to a cultural story",
        context_family="culture",
        premise="A short fictional story or folk-tale extract presents a character's choice and a value or theme that can be discussed without specialist knowledge.",
        learner_role="reader sharing a personal response and connecting it to a wider idea",
        partner_roles=("friend", "classmate", "cultural guide"),
        setting_slots=("fictional story extract", "character choice", "implied theme", "reflection prompt"),
        text_types=("story extract", "short reflection", "discussion exchange"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("culture", "education", "entertainment", "history"),
        outcomes=_outcomes(
            ("Can identify a character's action and give a simple personal reaction.", "a short reaction to the story", "a brief illustrated extract and sentence frames"),
            ("Can describe what a character did and say why it seems right or wrong.", "a short opinion with a simple reason", "the extract and a phrase bank"),
            ("Can summarize the character's choice, identify the implied theme, and connect it to a personal experience.", "a connected personal reflection", "the extract and reflection criteria"),
            ("Can analyse a theme across the fictional story, qualify a moral reading, and engage with an alternative view.", "a nuanced personal response grounded in the text", "the self-contained extract only"),
        ),
    ),
    ScenarioArchetype(
        id="everyday.give_and_receive_directions",
        title="Give or follow directions",
        context_family="everyday",
        premise="A fictional neighbourhood map or written instruction supplies all the landmarks, street names, and turn information needed to complete a route.",
        learner_role="person explaining or following a route using only the supplied map details",
        partner_roles=("passerby", "neighbour", "friend"),
        setting_slots=("fictional map", "start point", "destination", "one complication"),
        text_types=("neighbourhood map", "written directions", "street dialogue"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("daily_life", "travel", "culture", "sports", "entertainment"),
        outcomes=_outcomes(
            ("Can follow one or two direction steps using supplied landmarks.", "a short confirmed route", "a simple map and fixed direction phrases"),
            ("Can give or follow a short route using familiar landmarks and direction words.", "a brief set of accurate directions", "a clear map and a phrase bank"),
            ("Can explain a multi-step route, account for one complication, and confirm understanding.", "a clear complete set of directions", "the fictional map and task criteria only"),
            ("Can give precise directions, handle an unexpected obstacle, and adapt the route in real time.", "a revised route with a clear explanation of the change", "outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="everyday.ask_for_and_give_recommendations",
        title="Ask for and give a recommendation",
        context_family="everyday",
        premise="A fictional local context supplies options for restaurants, shops, events, or services, with simple ratings, features, and user comments.",
        learner_role="person asking for or giving a justified recommendation",
        partner_roles=("friend", "neighbour", "local guide"),
        setting_slots=("options with ratings", "requester's preferences", "one drawback", "one clear best choice"),
        text_types=("review snippets", "recommendation message", "conversation exchange"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "exam_preparation"),
        compatible_interest_ids=("daily_life", "travel", "entertainment", "culture"),
        outcomes=_outcomes(
            ("Can read a simple rating and suggest one option for a familiar need.", "a short suggestion", "labelled options and a fixed suggestion frame"),
            ("Can compare two options and suggest the better one with a simple reason.", "a brief recommendation with a reason", "a small review card and comparison phrases"),
            ("Can evaluate several options against stated preferences and recommend one with supporting evidence.", "a justified recommendation that addresses the drawback", "the review data and criteria"),
            ("Can weigh subtle trade-offs, qualify a recommendation, and respond to a challenge.", "a nuanced recommendation that acknowledges the drawback", "the evidence and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="travel.describe_a_place",
        title="Describe a fictional place",
        context_family="travel",
        premise="A fictional destination supplies all physical, cultural, and practical details needed for a description without specialist knowledge.",
        learner_role="traveler describing the place to someone who has not been there",
        partner_roles=("friend", "travel companion", "host"),
        setting_slots=("fictional destination", "key features", "practical details", "personal highlight"),
        text_types=("travel note", "postcard-style message", "description dialogue"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "exam_preparation"),
        compatible_interest_ids=("daily_life", "travel", "entertainment", "culture", "business"),
        outcomes=_outcomes(
            ("Can name a place and say one or two things about it.", "a short place description", "a labelled picture and sentence frames"),
            ("Can describe the main features of a fictional place using simple sentences.", "a brief description with two or three details", "a short fact card and phrase bank"),
            ("Can give an organised description of a fictional place, covering features, atmosphere, and a practical detail.", "a connected multi-point description", "the place details and task criteria only"),
            ("Can describe a fictional place vividly, contrast aspects, and include a qualified personal evaluation.", "a rich description with contrast and opinion", "the supplied details only"),
        ),
    ),
    ScenarioArchetype(
        id="travel.prepare_for_a_trip",
        title="Prepare for a fictional trip",
        context_family="travel",
        premise="A fictional trip brief supplies destination details, a checklist, visa or entry requirements, and a budget summary.",
        learner_role="traveler preparing by checking requirements and making a practical plan",
        partner_roles=("travel companion", "agent", "host"),
        setting_slots=("fictional destination", "entry requirements", "packing checklist", "budget"),
        text_types=("trip brief", "preparation checklist", "planning dialogue"),
        compatible_goal_ids=("travel_independence", "confident_conversation", "workplace_communication"),
        compatible_interest_ids=("travel", "daily_life", "culture", "entertainment"),
        outcomes=_outcomes(
            ("Can find key trip details such as what to bring and when to leave from a simple list.", "a short checklist confirmation", "a labelled trip card and sentence frames"),
            ("Can summarize the main preparation steps and ask one practical question.", "a brief preparation summary and a question", "a simple brief and phrase bank"),
            ("Can organise preparation steps, explain an entry requirement, and flag a potential problem.", "a clear preparation plan with a flagged issue", "the trip brief and task criteria only"),
            ("Can synthesize requirements, evaluate a budget constraint, and propose a contingency.", "a detailed preparation plan with a contingency", "the complete brief and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="work.give_and_respond_to_feedback",
        title="Give and respond to feedback",
        context_family="work",
        premise="A fictional piece of work has a clear stated goal and a reviewer's documented comments that can be addressed without specialist knowledge.",
        learner_role="colleague giving constructive feedback or responding to it professionally",
        partner_roles=("colleague", "team lead", "project partner"),
        setting_slots=("work output", "stated goal", "reviewer comments", "suggested next step"),
        text_types=("review note", "feedback exchange", "revision message"),
        compatible_goal_ids=("workplace_communication", "academic_study", "confident_conversation"),
        compatible_interest_ids=("business", "education", "technology", "science", "daily_life"),
        outcomes=_outcomes(
            ("Can identify one positive and one change from a simple review note.", "a short feedback acknowledgment", "labelled comments and fixed response frames"),
            ("Can summarize the main feedback and say what change to make.", "a brief feedback response with one action", "a short review note and useful phrases"),
            ("Can acknowledge strengths, address specific comments, and propose a concrete revision.", "a professional feedback exchange with a revision plan", "the review note and task criteria only"),
            ("Can evaluate feedback, distinguish minor from substantive points, and negotiate a revision scope.", "a calibrated response that accepts some and questions other feedback points", "the review document and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="work.handle_a_meeting",
        title="Participate in a short work meeting",
        context_family="work",
        premise="A fictional meeting agenda, notes, and action items supply all the information needed to contribute, summarize, or follow up.",
        learner_role="team member contributing a point, summarizing a decision, or confirming an action",
        partner_roles=("colleague", "team lead", "external partner"),
        setting_slots=("agenda item", "discussion points", "decision", "action item"),
        text_types=("meeting agenda", "meeting notes", "follow-up message"),
        compatible_goal_ids=("workplace_communication", "confident_conversation", "academic_study"),
        compatible_interest_ids=("business", "technology", "education", "science", "daily_life"),
        outcomes=_outcomes(
            ("Can find a decision and an action item from a simple meeting note.", "a short action confirmation", "a labelled notes card and sentence frames"),
            ("Can summarize one meeting decision and say who does what next.", "a brief meeting summary and action note", "a clear agenda and phrase bank"),
            ("Can summarize the discussion, explain a decision, and confirm responsibilities with deadlines.", "a structured meeting follow-up note", "the meeting notes and task criteria only"),
            ("Can synthesize multiple agenda items, evaluate a disputed point, and draft a clear action plan.", "a comprehensive follow-up that resolves ambiguity", "the complete notes and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="study.use_a_reference_source",
        title="Use a reference source for a task",
        context_family="study",
        premise="A fictional reference extract, glossary, or chart supplies all the factual content needed to answer a specific question without reading comprehension beyond the extract.",
        learner_role="learner locating and using information from the supplied source",
        partner_roles=("classmate", "teacher", "study partner"),
        setting_slots=("source type", "specific question", "relevant extract section", "one distractor detail"),
        text_types=("reference extract", "glossary", "information exchange"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication"),
        compatible_interest_ids=("education", "science", "technology", "history", "culture"),
        outcomes=_outcomes(
            ("Can find one specific fact in a short labelled reference extract.", "a short factual answer with a source location", "a highlighted extract and fixed answer frames"),
            ("Can locate and use relevant information from a short reference to answer a simple question.", "a brief answer supported by the source", "a short reference and useful phrases"),
            ("Can select relevant information from a longer extract, paraphrase it, and apply it to the task question.", "an accurate task answer with a source reference", "the reference and task criteria"),
            ("Can synthesize information from multiple sections, resolve apparent contradictions, and construct a supported answer.", "a nuanced answer that handles contradictions", "the complete source and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="study.give_a_short_presentation",
        title="Give a short presentation",
        context_family="study",
        premise="A fictional topic brief and supplied notes give the learner all the content needed for a short structured spoken or written presentation.",
        learner_role="student giving a clear, organised short presentation on a fictional topic",
        partner_roles=("classmate", "teacher", "audience member"),
        setting_slots=("fictional topic", "key points", "one supporting detail each", "a closing statement"),
        text_types=("presentation notes", "slide summary", "audience Q&A"),
        compatible_goal_ids=("academic_study", "exam_preparation", "workplace_communication", "confident_conversation"),
        compatible_interest_ids=("education", "science", "technology", "culture", "history", "business"),
        outcomes=_outcomes(
            ("Can state a topic and mention two key points from supplied notes.", "a very short two-point summary", "labelled notes and fixed opening and closing frames"),
            ("Can give a short organised presentation using supplied notes with an opening, two points, and a close.", "a brief structured presentation", "structured notes and a phrase bank"),
            ("Can present a topic clearly with an introduction, developed supporting points, and a conclusion.", "a coherent short presentation with evidence", "the notes and presentation criteria"),
            ("Can deliver a structured presentation, anticipate a challenging question, and respond constructively.", "a complete presentation with a prepared Q&A response", "the topic brief and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="technology.communicate_a_digital_process",
        title="Explain a digital process",
        context_family="technology",
        premise="A fictional step-by-step digital workflow is fully documented with screenshots described in text and decision points.",
        learner_role="user explaining the process to someone who has not done it before",
        partner_roles=("colleague", "friend", "help-desk contact"),
        setting_slots=("fictional process", "documented steps", "decision point", "common mistake"),
        text_types=("process guide", "help article", "explanation dialogue"),
        compatible_goal_ids=("workplace_communication", "confident_conversation", "academic_study"),
        compatible_interest_ids=("technology", "business", "education", "daily_life"),
        outcomes=_outcomes(
            ("Can identify the first and last step of a simple documented process.", "a short first-and-last-step summary", "a numbered steps card and fixed sequence frames"),
            ("Can explain the key steps of a familiar process using simple sequence language.", "a brief step-by-step explanation", "the process guide and phrase bank"),
            ("Can explain a digital process clearly, flag the decision point, and warn about the common mistake.", "a complete process explanation with a caution", "the documented workflow and outcome criteria"),
            ("Can explain a multi-path process, justify a decision at a branch point, and troubleshoot an anticipated failure.", "a precise explanation covering the decision branch and recovery", "the complete workflow and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="technology.evaluate_digital_information",
        title="Evaluate a piece of digital information",
        context_family="technology",
        premise="A fictional online post, notification, or article contains a claim that can be evaluated using only the supplied context and stated source details.",
        learner_role="user deciding whether the information is reliable and explaining why",
        partner_roles=("friend", "colleague", "classmate"),
        setting_slots=("fictional content piece", "source details", "one reliable signal", "one unreliable signal"),
        text_types=("online post", "notification", "evaluation dialogue"),
        compatible_goal_ids=("academic_study", "exam_preparation", "confident_conversation", "workplace_communication"),
        compatible_interest_ids=("technology", "education", "science", "daily_life"),
        outcomes=_outcomes(
            ("Can identify whether a source detail looks trustworthy or suspicious from a simple label.", "a short trust judgement", "labelled source signals and fixed judgement frames"),
            ("Can describe one reliable and one unreliable signal in a short fictional piece.", "a brief reliability note with two signals", "the content card and useful phrases"),
            ("Can evaluate the reliability of a fictional piece using supplied signals and give a supported judgement.", "a clear reliability evaluation with evidence", "the fictional content and criteria"),
            ("Can weigh conflicting signals, qualify a reliability judgement, and suggest a proportionate response.", "a nuanced reliability assessment with a recommended action", "the complete fictional piece and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="entertainment.plan_a_fictional_event",
        title="Plan a fictional entertainment event",
        context_family="entertainment",
        premise="A fictional group wants to organise an event such as a film night, gaming session, or music gathering, and must agree on format, time, and practical details.",
        learner_role="participant helping the group reach a workable event plan",
        partner_roles=("friend", "club member", "flatmate"),
        setting_slots=("event type options", "participant preferences", "venue or platform", "one constraint"),
        text_types=("group chat extract", "event notice", "planning dialogue"),
        compatible_goal_ids=("confident_conversation", "travel_independence", "exam_preparation"),
        compatible_interest_ids=("entertainment", "daily_life", "culture", "music", "sports"),
        outcomes=_outcomes(
            ("Can choose an event type and state a simple time preference.", "a short event plan", "labelled options and fixed planning frames"),
            ("Can suggest an event format and agree on a time that suits the group.", "a brief agreed event plan", "a short options list and phrase bank"),
            ("Can compare options against constraints and help the group agree on a practical event plan.", "a connected event proposal addressing the constraint", "the options and outcome criteria"),
            ("Can negotiate format, timing, and practical logistics for a group event, balancing competing preferences.", "a detailed agreed event plan with reasoning", "the complete case details and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="entertainment.review_a_fictional_product",
        title="Review a fictional creative product",
        context_family="entertainment",
        premise="A fictional game, album, film, or show supplies a complete feature list, storyline summary, and a set of fictional audience reactions.",
        learner_role="reviewer using only supplied details to write or discuss a fair evaluation",
        partner_roles=("friend", "online reviewer", "classmate"),
        setting_slots=("fictional product", "feature summary", "audience reactions", "one weak point"),
        text_types=("review draft", "rating card", "review discussion"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("entertainment", "culture", "technology", "music"),
        outcomes=_outcomes(
            ("Can name one good thing and one bad thing about a fictional product.", "a short two-point reaction", "a labelled feature card and fixed evaluation frames"),
            ("Can summarize the main features and give a simple overall judgement.", "a brief review with a rating and one reason", "a feature summary and comparison phrases"),
            ("Can write a balanced review using supplied features and audience reactions to support an overall judgement.", "a structured review covering strengths and the weak point", "the feature data and criteria"),
            ("Can craft a nuanced review, weigh contradictory reactions, and qualify an overall recommendation.", "a qualified review that addresses audience disagreement", "the complete fictional product data only"),
        ),
    ),
    ScenarioArchetype(
        id="sports.discuss_performance",
        title="Discuss a fictional performance",
        context_family="sports",
        premise="A fictional athlete or team performance record supplies stats, coach comments, and contextual background needed to analyse what went well and what to improve.",
        learner_role="participant or commentator explaining the performance using only supplied evidence",
        partner_roles=("teammate", "coach", "sports journalist"),
        setting_slots=("fictional athlete or team", "performance stats", "coach comment", "area for improvement"),
        text_types=("performance summary", "stat table", "interview extract"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("sports", "entertainment", "education", "daily_life"),
        outcomes=_outcomes(
            ("Can identify one strength and one weakness from a simple performance card.", "a short strength-and-weakness statement", "a labelled stat card and fixed evaluation frames"),
            ("Can describe the main performance and say what went well and what could improve.", "a brief performance summary with two evaluations", "a short stat table and phrase bank"),
            ("Can analyse a performance record, support evaluations with evidence, and suggest a priority improvement.", "a structured evidence-based performance review", "the complete record and task criteria only"),
            ("Can synthesize stats and qualitative comments to deliver a nuanced performance assessment that balances praise with constructive critique.", "a balanced analytical review addressing contradictory evidence", "the full supplied record and outcome criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="sports.explain_fictional_rules",
        title="Explain the rules of a fictional sport or game",
        context_family="sports",
        premise="A fictional sport or game has a complete rulebook extract that supplies all scoring, play, and boundary rules needed without requiring prior knowledge.",
        learner_role="participant explaining the rules clearly to a newcomer",
        partner_roles=("new player", "curious friend", "referee"),
        setting_slots=("fictional sport", "core rules", "scoring system", "one tricky rule"),
        text_types=("rulebook extract", "rule explanation dialogue", "referee note"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation"),
        compatible_interest_ids=("sports", "education", "entertainment", "daily_life"),
        outcomes=_outcomes(
            ("Can identify the main goal of the fictional sport and one basic rule.", "a short goal-and-rule statement", "a labelled rulebook card and sentence frames"),
            ("Can explain the core rules and scoring of the fictional sport in simple terms.", "a brief clear rules explanation", "the rulebook extract and a phrase bank"),
            ("Can explain the full rules, scoring, and the tricky rule clearly to someone new.", "a complete rules explanation covering all key points", "the rulebook and outcome criteria"),
            ("Can explain the complete rules, handle a rule dispute using the text, and negotiate an edge case.", "a complete rules explanation that resolves the edge case", "the full rulebook extract and criteria only"),
        ),
    ),
    ScenarioArchetype(
        id="culture.interpret_a_cultural_practice",
        title="Interpret a cultural practice",
        context_family="culture",
        premise="A fictional community's documented practice, celebration, or custom supplies all the relevant context, history, and steps needed for an explanation.",
        learner_role="person explaining the practice and its significance to an outsider",
        partner_roles=("visitor", "curious classmate", "community member"),
        setting_slots=("fictional practice", "origin details", "steps or elements", "significance statement"),
        text_types=("community guide", "cultural note", "explanation dialogue"),
        compatible_goal_ids=("confident_conversation", "academic_study", "exam_preparation", "travel_independence"),
        compatible_interest_ids=("culture", "education", "travel", "history", "entertainment"),
        outcomes=_outcomes(
            ("Can name the practice and say one thing it involves.", "a short practice identification", "a labelled culture card and sentence frames"),
            ("Can describe the main steps or elements of the fictional practice and say why it matters.", "a brief practice description with a significance statement", "a short guide and useful phrases"),
            ("Can explain the origin, steps, and significance of the fictional practice clearly to an outsider.", "a connected cultural explanation", "the fictional guide and outcome criteria"),
            ("Can explain the practice, address a misunderstanding about it, and discuss how it has changed over time.", "a nuanced cultural explanation that corrects a misconception", "the complete guide and criteria only"),
        ),
    ),
)

